name: Azure Static Web Apps CI/CD (PROD)

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy (PROD)

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Create frontend env file
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" > frontend/.env.production
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> frontend/.env.production
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          ORYX_NODE_VERSION: "20.19.0"
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_FIELD_0A83BBB10 }}
          action: "upload"
          app_location: "./frontend"
          output_location: "dist"
          api_location: "api"   # keep empty unless you really have Azure Functions
